#!/bin/sh

start() {
	printf "Starting Bluetooth: "

	# Attach Bluetooth HCI UART
	/usr/bin/btattach -B /dev/ttyAMA0 -P bcm -S 115200 &
	sleep 2

	# Start Bluetooth daemon
	/usr/libexec/bluetooth/bluetoothd &
	sleep 2

	# Power on Bluetooth
	/usr/bin/bluetoothctl power on
	/usr/bin/bluetoothctl agent on
	/usr/bin/bluetoothctl default-agent

	echo "OK"
}

stop() {
	printf "Stopping Bluetooth: "
	killall bluetoothd
	killall btattach
	echo "OK"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
